FROM python:3.9-slim

RUN pip install --no-cache-dir \
    pandas==2.1.4 \
    pydantic==2.5.3 \
    boto3==1.34.95 \
    xgboost==2.0.3 \
    scikit-learn==1.3.2 \
    numpy==1.26.2 \
    kfp==2.7.0
