FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip && \
    pip install --default-timeout=1000 --retries=10 --no-cache-dir -r /app/requirements.txt

COPY src /app/src

ENV PYTHONPATH=/app
