"""Drift-driven retraining trigger for the GPON failure prediction pipeline.

This script is the bridge between monitoring and retraining:

1. Read the latest drift metrics exported by ``monitoring.drift_detection``.
2. Evaluate a transparent set of trigger rules.
3. Optionally submit a new Kubeflow Pipelines run.
4. Publish retraining decision metrics for Prometheus/Grafana.

By default the script runs in dry-run mode, so it is safe to execute while
you tune thresholds and cooldown windows.
"""

import argparse
import logging
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

from prometheus_client import CollectorRegistry, Gauge, write_to_textfile
import yaml

logger = logging.getLogger(__name__)

DEFAULT_CONFIG_PATH = Path("retraining/retraining_config.example.yaml")
DEFAULT_DRIFT_METRICS_PATH = Path("monitoring/prometheus_textfile/drift_detection.prom")
DEFAULT_TRIGGER_METRICS_PATH = Path("monitoring/prometheus_textfile/retraining_trigger.prom")
DEFAULT_PIPELINE_PACKAGE_PATH = Path("pipelines/pipeline.yaml")
DEFAULT_PIPELINE_HOST = "http://localhost:8080"
DEFAULT_PIPELINE_EXPERIMENT_NAME = "gpon-retraining"
DEFAULT_RUN_NAME_PREFIX = "gpon-retrain"
DEFAULT_INPUT_CSV_PATH = "s3://gpon-telemetry/raw/telemetry.csv"
DEFAULT_TEST_SIZE = 0.2
DEFAULT_AUC_THRESHOLD = 0.75
DEFAULT_MIN_DRIFTED_COLUMNS = 3
DEFAULT_MIN_DRIFTED_FRACTION = 0.30
DEFAULT_COOLDOWN_MINUTES = 120


@dataclass
class TriggerDecision:
    """Container for retraining trigger results."""

    should_trigger: bool
    reasons: List[str]
    dataset_drift_detected: bool
    drift_check_success: bool
    drifted_columns_count: int
    drifted_columns_fraction: float
    cooldown_active: bool
    last_submission_age_minutes: Optional[float]


def configure_logging(level: int = logging.INFO) -> None:
    """Set up structured logging for the retraining trigger."""
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[logging.StreamHandler(sys.stdout)],
    )


def load_yaml_config(path: Optional[Path]) -> Dict:
    """Load an optional YAML config file."""
    if path is None:
        return {}
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}

    if not isinstance(data, dict):
        raise ValueError(f"Expected YAML mapping at {path}, got: {type(data).__name__}")
    return data


def _flatten_config(config: Dict) -> Dict[str, object]:
    """Normalize nested YAML config sections into a flat mapping."""
    pipeline = config.get("pipeline", {}) or {}
    thresholds = config.get("thresholds", {}) or {}

    return {
        "drift_metrics_path": config.get("drift_metrics_path"),
        "trigger_metrics_path": config.get("trigger_metrics_path"),
        "pipeline_host": pipeline.get("host"),
        "pipeline_package_path": pipeline.get("package_path"),
        "pipeline_experiment_name": pipeline.get("experiment_name"),
        "run_name_prefix": pipeline.get("run_name_prefix"),
        "input_csv_path": pipeline.get("input_csv_path"),
        "test_size": pipeline.get("test_size"),
        "auc_threshold": pipeline.get("auc_threshold"),
        "require_dataset_drift": thresholds.get("require_dataset_drift"),
        "min_drifted_columns": thresholds.get("min_drifted_columns"),
        "min_drifted_fraction": thresholds.get("min_drifted_fraction"),
        "cooldown_minutes": thresholds.get("cooldown_minutes"),
    }


def _coalesce(*values):
    """Return the first non-None value."""
    for value in values:
        if value is not None:
            return value
    return None


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments with optional YAML config defaults."""
    bootstrap = argparse.ArgumentParser(add_help=False)
    bootstrap.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG_PATH,
        help="Optional YAML config file for retraining trigger settings.",
    )
    bootstrap_args, remaining = bootstrap.parse_known_args()
    config = _flatten_config(load_yaml_config(bootstrap_args.config))

    parser = argparse.ArgumentParser(
        description="Evaluate drift metrics and optionally trigger a Kubeflow retraining run.",
        parents=[bootstrap],
    )
    parser.add_argument(
        "--drift-metrics",
        type=Path,
        default=Path(
            _coalesce(config.get("drift_metrics_path"), DEFAULT_DRIFT_METRICS_PATH)
        ),
        help="Prometheus textfile generated by monitoring.drift_detection.",
    )
    parser.add_argument(
        "--trigger-metrics",
        type=Path,
        default=Path(
            _coalesce(config.get("trigger_metrics_path"), DEFAULT_TRIGGER_METRICS_PATH)
        ),
        help="Prometheus textfile written by this retraining trigger.",
    )
    parser.add_argument(
        "--pipeline-host",
        type=str,
        default=_coalesce(config.get("pipeline_host"), DEFAULT_PIPELINE_HOST),
        help="Kubeflow Pipelines host URL.",
    )
    parser.add_argument(
        "--pipeline-package",
        type=Path,
        default=Path(
            _coalesce(config.get("pipeline_package_path"), DEFAULT_PIPELINE_PACKAGE_PATH)
        ),
        help="Compiled pipeline package to submit when retraining is triggered.",
    )
    parser.add_argument(
        "--experiment-name",
        type=str,
        default=_coalesce(
            config.get("pipeline_experiment_name"),
            DEFAULT_PIPELINE_EXPERIMENT_NAME,
        ),
        help="Kubeflow Pipelines experiment name used for retraining runs.",
    )
    parser.add_argument(
        "--run-name-prefix",
        type=str,
        default=_coalesce(config.get("run_name_prefix"), DEFAULT_RUN_NAME_PREFIX),
        help="Prefix used for retraining run names.",
    )
    parser.add_argument(
        "--input-csv-path",
        type=str,
        default=_coalesce(config.get("input_csv_path"), DEFAULT_INPUT_CSV_PATH),
        help="Raw telemetry CSV path passed to the pipeline.",
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=float(_coalesce(config.get("test_size"), DEFAULT_TEST_SIZE)),
        help="Test split passed to the pipeline.",
    )
    parser.add_argument(
        "--auc-threshold",
        type=float,
        default=float(_coalesce(config.get("auc_threshold"), DEFAULT_AUC_THRESHOLD)),
        help="Quality gate threshold passed to the pipeline.",
    )
    parser.add_argument(
        "--require-dataset-drift",
        dest="require_dataset_drift",
        action="store_true",
        default=bool(
            _coalesce(config.get("require_dataset_drift"), True)
        ),
        help="Require dataset-level drift before retraining is allowed.",
    )
    parser.add_argument(
        "--allow-feature-only-trigger",
        dest="require_dataset_drift",
        action="store_false",
        help="Allow retraining based on per-feature drift counts/fraction alone.",
    )
    parser.add_argument(
        "--min-drifted-columns",
        type=int,
        default=int(
            _coalesce(config.get("min_drifted_columns"), DEFAULT_MIN_DRIFTED_COLUMNS)
        ),
        help="Minimum number of drifted feature columns required to trigger retraining.",
    )
    parser.add_argument(
        "--min-drifted-fraction",
        type=float,
        default=float(
            _coalesce(
                config.get("min_drifted_fraction"),
                DEFAULT_MIN_DRIFTED_FRACTION,
            )
        ),
        help="Minimum fraction of drifted shared feature columns required to trigger retraining.",
    )
    parser.add_argument(
        "--cooldown-minutes",
        type=int,
        default=int(
            _coalesce(config.get("cooldown_minutes"), DEFAULT_COOLDOWN_MINUTES)
        ),
        help="Do not submit a new retraining run if the last submission is younger than this window.",
    )
    parser.add_argument(
        "--submit",
        action="store_true",
        default=False,
        help="Actually submit a Kubeflow Pipelines run when trigger conditions are met.",
    )
    parser.add_argument(
        "--namespace",
        type=str,
        default=None,
        help="Optional namespace passed to the Kubeflow Pipelines client.",
    )
    return parser.parse_args(remaining)


def parse_prometheus_textfile(path: Path) -> Dict[str, float]:
    """Read simple scalar metrics from a Prometheus textfile."""
    if not path.exists():
        raise FileNotFoundError(f"Metrics file not found: {path}")

    metrics: Dict[str, float] = {}
    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue

            parts = line.split()
            if len(parts) != 2:
                continue

            metric_token, value_token = parts
            if "{" in metric_token:
                # Ignore labeled metrics here; trigger logic only uses scalar values.
                continue

            try:
                metrics[metric_token] = float(value_token)
            except ValueError:
                logger.debug("Skipping non-numeric metric line: %s", line)

    logger.info("Loaded %d scalar metrics from %s", len(metrics), path)
    return metrics


def evaluate_trigger(
    drift_metrics: Dict[str, float],
    previous_trigger_metrics: Dict[str, float],
    require_dataset_drift: bool,
    min_drifted_columns: int,
    min_drifted_fraction: float,
    cooldown_minutes: int,
) -> TriggerDecision:
    """Evaluate whether a retraining run should be triggered."""
    reasons: List[str] = []

    drift_check_success = drift_metrics.get("gpon_drift_check_success", 0.0) >= 0.5
    dataset_drift_detected = drift_metrics.get("gpon_data_drift_detected", 0.0) >= 0.5
    drifted_columns_count = int(drift_metrics.get("gpon_drifted_columns_count", 0.0))
    drifted_columns_fraction = float(
        drift_metrics.get("gpon_drifted_columns_fraction", 0.0)
    )

    if not drift_check_success:
        reasons.append("last drift check did not complete successfully")
    if require_dataset_drift and not dataset_drift_detected:
        reasons.append("dataset-level drift is not currently detected")
    if drifted_columns_count < min_drifted_columns:
        reasons.append(
            f"drifted column count {drifted_columns_count} is below the threshold {min_drifted_columns}"
        )
    if drifted_columns_fraction < min_drifted_fraction:
        reasons.append(
            "drifted column fraction "
            f"{drifted_columns_fraction:.3f} is below the threshold {min_drifted_fraction:.3f}"
        )

    cooldown_active = False
    last_submission_age_minutes: Optional[float] = None
    last_submission_ts = previous_trigger_metrics.get(
        "gpon_retraining_last_submission_timestamp_seconds"
    )
    if last_submission_ts:
        last_submission_age_minutes = (time.time() - last_submission_ts) / 60.0
        if last_submission_age_minutes < float(cooldown_minutes):
            cooldown_active = True
            reasons.append(
                f"cooldown is active ({last_submission_age_minutes:.1f} min < {cooldown_minutes} min)"
            )

    should_trigger = not reasons
    return TriggerDecision(
        should_trigger=should_trigger,
        reasons=reasons,
        dataset_drift_detected=dataset_drift_detected,
        drift_check_success=drift_check_success,
        drifted_columns_count=drifted_columns_count,
        drifted_columns_fraction=drifted_columns_fraction,
        cooldown_active=cooldown_active,
        last_submission_age_minutes=last_submission_age_minutes,
    )


def submit_retraining_run(
    pipeline_host: str,
    pipeline_package: Path,
    experiment_name: str,
    run_name_prefix: str,
    input_csv_path: str,
    test_size: float,
    auc_threshold: float,
    namespace: Optional[str],
) -> Optional[str]:
    """Submit a retraining run to Kubeflow Pipelines."""
    if not pipeline_package.exists():
        raise FileNotFoundError(f"Pipeline package not found: {pipeline_package}")

    from kfp import Client

    client_kwargs = {"host": pipeline_host}
    if namespace:
        client_kwargs["namespace"] = namespace

    logger.info("Connecting to Kubeflow Pipelines at %s", pipeline_host)
    client = Client(**client_kwargs)
    run_name = f"{run_name_prefix}-{time.strftime('%Y%m%d-%H%M%S')}"

    logger.info(
        "Submitting retraining run '%s' from package %s",
        run_name,
        pipeline_package,
    )
    run = client.create_run_from_pipeline_package(
        str(pipeline_package),
        arguments={
            "input_csv_path": input_csv_path,
            "test_size": test_size,
            "auc_threshold": auc_threshold,
        },
        run_name=run_name,
        experiment_name=experiment_name,
    )

    run_id = getattr(run, "run_id", None)
    if run_id is None:
        run_id = getattr(getattr(run, "run", None), "run_id", None)

    logger.info("Kubeflow retraining run submitted successfully (run_id=%s)", run_id)
    return run_id


def write_trigger_metrics(
    output_path: Path,
    decision: TriggerDecision,
    min_drifted_columns: int,
    min_drifted_fraction: float,
    submitted: bool,
    submission_success: bool,
    last_submission_timestamp: Optional[float],
) -> Path:
    """Write retraining trigger metrics for Prometheus/Grafana."""
    registry = CollectorRegistry()

    should_trigger_metric = Gauge(
        "gpon_retraining_should_trigger",
        "Whether the latest retraining evaluation decided a new run should be triggered.",
        registry=registry,
    )
    dataset_drift_metric = Gauge(
        "gpon_retraining_dataset_drift_detected",
        "Whether dataset-level drift was present in the latest retraining evaluation.",
        registry=registry,
    )
    drift_check_success_metric = Gauge(
        "gpon_retraining_drift_check_success",
        "Whether the latest drift check was successful from the retraining trigger perspective.",
        registry=registry,
    )
    drifted_columns_count_metric = Gauge(
        "gpon_retraining_drifted_columns_count",
        "Drifted feature column count used by the latest retraining evaluation.",
        registry=registry,
    )
    drifted_fraction_metric = Gauge(
        "gpon_retraining_drifted_columns_fraction",
        "Drifted feature fraction used by the latest retraining evaluation.",
        registry=registry,
    )
    cooldown_metric = Gauge(
        "gpon_retraining_cooldown_active",
        "Whether the retraining cooldown blocked a new submission.",
        registry=registry,
    )
    submitted_metric = Gauge(
        "gpon_retraining_submission_attempted",
        "Whether the latest retraining evaluation attempted a KFP submission.",
        registry=registry,
    )
    submission_success_metric = Gauge(
        "gpon_retraining_submission_success",
        "Whether the latest retraining submission attempt succeeded.",
        registry=registry,
    )
    last_decision_metric = Gauge(
        "gpon_retraining_last_decision_timestamp_seconds",
        "Unix timestamp of the latest retraining evaluation.",
        registry=registry,
    )
    last_submission_metric = Gauge(
        "gpon_retraining_last_submission_timestamp_seconds",
        "Unix timestamp of the latest successful retraining submission.",
        registry=registry,
    )
    decision_rule_metric = Gauge(
        "gpon_retraining_rule_passed",
        "Whether an individual retraining rule passed in the latest evaluation.",
        labelnames=["rule"],
        registry=registry,
    )

    should_trigger_metric.set(1.0 if decision.should_trigger else 0.0)
    dataset_drift_metric.set(1.0 if decision.dataset_drift_detected else 0.0)
    drift_check_success_metric.set(1.0 if decision.drift_check_success else 0.0)
    drifted_columns_count_metric.set(float(decision.drifted_columns_count))
    drifted_fraction_metric.set(float(decision.drifted_columns_fraction))
    cooldown_metric.set(1.0 if decision.cooldown_active else 0.0)
    submitted_metric.set(1.0 if submitted else 0.0)
    submission_success_metric.set(1.0 if submission_success else 0.0)
    last_decision_metric.set(time.time())
    if last_submission_timestamp is not None:
        last_submission_metric.set(last_submission_timestamp)

    decision_rule_metric.labels(rule="drift_check_success").set(
        1.0 if decision.drift_check_success else 0.0
    )
    decision_rule_metric.labels(rule="dataset_drift").set(
        1.0 if decision.dataset_drift_detected else 0.0
    )
    decision_rule_metric.labels(rule="cooldown_clear").set(
        0.0 if decision.cooldown_active else 1.0
    )
    decision_rule_metric.labels(rule="column_count_threshold").set(
        1.0 if decision.drifted_columns_count >= min_drifted_columns else 0.0
    )
    decision_rule_metric.labels(rule="fraction_threshold").set(
        1.0 if decision.drifted_columns_fraction >= min_drifted_fraction else 0.0
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_to_textfile(str(output_path), registry)
    logger.info("Retraining trigger metrics written to %s", output_path)
    return output_path


def main() -> None:
    """CLI entry-point for retraining trigger evaluation."""
    args = parse_args()
    configure_logging()

    logger.info("=== Retraining Trigger Evaluation START ===")
    drift_metrics = parse_prometheus_textfile(args.drift_metrics)
    previous_trigger_metrics: Dict[str, float] = {}
    if args.trigger_metrics.exists():
        previous_trigger_metrics = parse_prometheus_textfile(args.trigger_metrics)

    decision = evaluate_trigger(
        drift_metrics=drift_metrics,
        previous_trigger_metrics=previous_trigger_metrics,
        require_dataset_drift=args.require_dataset_drift,
        min_drifted_columns=args.min_drifted_columns,
        min_drifted_fraction=args.min_drifted_fraction,
        cooldown_minutes=args.cooldown_minutes,
    )

    logger.info(
        "Trigger decision: should_trigger=%s, drift_count=%d, drift_fraction=%.3f",
        decision.should_trigger,
        decision.drifted_columns_count,
        decision.drifted_columns_fraction,
    )
    if decision.reasons:
        for reason in decision.reasons:
            logger.info("Decision detail: %s", reason)

    submitted = False
    submission_success = False
    last_submission_timestamp: Optional[float] = previous_trigger_metrics.get(
        "gpon_retraining_last_submission_timestamp_seconds"
    )

    try:
        if args.submit and decision.should_trigger:
            submitted = True
            submit_retraining_run(
                pipeline_host=args.pipeline_host,
                pipeline_package=args.pipeline_package,
                experiment_name=args.experiment_name,
                run_name_prefix=args.run_name_prefix,
                input_csv_path=args.input_csv_path,
                test_size=args.test_size,
                auc_threshold=args.auc_threshold,
                namespace=args.namespace,
            )
            submission_success = True
            last_submission_timestamp = time.time()
        elif args.submit:
            logger.info("Submission skipped because trigger conditions were not met")
        else:
            logger.info("Dry-run mode: no Kubeflow run submission requested")
    finally:
        write_trigger_metrics(
            output_path=args.trigger_metrics,
            decision=decision,
            min_drifted_columns=args.min_drifted_columns,
            min_drifted_fraction=args.min_drifted_fraction,
            submitted=submitted,
            submission_success=submission_success,
            last_submission_timestamp=last_submission_timestamp,
        )

    logger.info("=== Retraining Trigger Evaluation COMPLETE ===")


if __name__ == "__main__":
    main()
